import 'dart:io';

import 'package:geekhaven/Models/pdf_model.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart';

class Traveller {
  final String name;
  final String email;
  final String tripExperience;
  final double rating;

  Traveller({
    required this.name,
    required this.email,
    required this.tripExperience,
    required this.rating,
  });
}

class PdfTravellerApi {
  static Future<File> generate(List<Traveller> travellers) async {
    final pdf = Document();

    pdf.addPage(
      MultiPage(
        build: (context) => [
          buildHeader(),
          SizedBox(height: 3 * PdfPageFormat.cm),
          buildTitle(),
          buildTravellerTable(travellers),
          Divider(),
        ],
        footer: (context) => buildFooter(),
      ),
    );

    return PdfApi.saveDocument(name: 'travellers_report.pdf', pdf: pdf);
  }

  static Widget buildHeader() => Column(
    crossAxisAlignment: CrossAxisAlignment.start,
    children: [
      Text(
        'TRAVELLER REPORT',
        style: TextStyle(fontSize: 24, fontWeight: FontWeight.bold),
      ),
      SizedBox(height: 1 * PdfPageFormat.cm),
      Text('Generated on: ${Utils.formatDate(DateTime.now())}'),
    ],
  );

  static Widget buildTitle() => Column(
    crossAxisAlignment: CrossAxisAlignment.start,
    children: [
      Text(
        'Traveller List',
        style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold),
      ),
      SizedBox(height: 0.8 * PdfPageFormat.cm),
    ],
  );

  static Widget buildTravellerTable(List<Traveller> travellers) {
    final headers = ['Name', 'Email', 'Trip Experience', 'Rating'];
    final data = travellers.map((traveller) {
      return [
        traveller.name,
        traveller.email,
        traveller.tripExperience,
        '${traveller.rating.toStringAsFixed(1)} / 5',
      ];
    }).toList();

    return Table.fromTextArray(
      headers: headers,
      data: data,
      border: null,
      headerStyle: TextStyle(fontWeight: FontWeight.bold),
      headerDecoration: BoxDecoration(color: PdfColors.grey300),
      cellHeight: 30,
      cellAlignments: {
        0: Alignment.centerLeft,
        1: Alignment.centerLeft,
        2: Alignment.centerLeft,
        3: Alignment.centerRight,
      },
    );
  }

  static Widget buildFooter() => Column(
    crossAxisAlignment: CrossAxisAlignment.center,
    children: [
      Divider(),
      SizedBox(height: 2 * PdfPageFormat.mm),
      Text('Generated by Geekhaven '),
      SizedBox(height: 1 * PdfPageFormat.mm),
      Text('Contact: support@travellerapp.com'),
    ],
  );
}

class Utils {
  static String formatDate(DateTime date) {
    return '${date.day}/${date.month}/${date.year}';
  }
}
